--- # Start of yaml
- hosts: rhel
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no

  tasks:
  - name: Installing HTTPD server on RHEL/CENTOS servers
    yum:
      name: httpd
      state: present
    notify:
    - startservice
  
  handlers:
  - name: startservice
    service:
      name: httpd
      state: restarted 

