--- # Start of yaml
- hosts: rhel           # Hosts or pods that
  remote_user: ansible  # Who is the sudo user?
  become: yes           # Is sudo privilege required?
  become_method: sudo   # What is the sudo method?
  connection: ssh       # Autherization conn type
  gather_facts: no      # Get host details/facts

  tasks:
  - name: Installing HTTPD server and ELINKS on RHEL/CENTOS servers
    yum:
      name: [httpd, elinks]
      state: present
    notify:
    - startservice
  
  handlers:
  - name: startservice
    service:
      name: httpd
      state: restarted 

